const START_POINT_DATA = [
  {
    key: "특별/광역시",
    value: "특별/광역시",
    disabled: false,
    options: [
      { key: "서울", value: "서울" },
      { key: "부산", value: "부산" },
      { key: "대구", value: "대구" },
      { key: "인천", value: "인천" },
      { key: "광주", value: "광주" },
      { key: "대전", value: "대전" },
      { key: "울산", value: "울산" },
      { key: "세종", value: "세종" },
    ],
  },
  {
    key: "경기도",
    value: "경기도",
    disabled: false,
    options: [
      { key: "수원", value: "경기도 수원" },
      { key: "성남", value: "경기도 성남" },
      { key: "의정부", value: "경기도 의정부" },
      { key: "안양", value: "경기도 안양" },
      { key: "부천", value: "경기도 부천" },
      { key: "광명", value: "경기도 광명" },
      { key: "평택", value: "경기도 평택" },
      { key: "동두천", value: "경기도 동두천" },
      { key: "안산", value: "경기도 안산" },
      { key: "고양", value: "경기도 고양" },
      { key: "과천", value: "경기도 과천" },
      { key: "구리", value: "경기도 구리" },
      { key: "남양주", value: "경기도 남양주" },
      { key: "오산", value: "경기도 오산" },
      { key: "시흥", value: "경기도 시흥" },
      { key: "군포", value: "경기도 군포" },
      { key: "의왕", value: "경기도 의왕" },
      { key: "하남", value: "경기도 하남" },
      { key: "용인", value: "경기도 용인" },
      { key: "파주", value: "경기도 파주" },
      { key: "이천", value: "경기도 이천" },
      { key: "안성", value: "경기도 안성" },
      { key: "김포", value: "경기도 김포" },
      { key: "화성", value: "경기도 화성" },
      { key: "광주", value: "경기도 광주" },
      { key: "양주", value: "경기도 양주" },
      { key: "포천", value: "경기도 포천" },
      { key: "여주", value: "경기도 여주" },
      { key: "연천", value: "경기도 연천" },
      { key: "가평", value: "경기도 가평" },
      { key: "양평", value: "경기도 양평" },
    ],
  },
  {
    key: "강원도",
    value: "강원도",
    disabled: false,
    options: [
      { key: "춘천", value: "강원도 춘천" },
      { key: "원주", value: "강원도 원주" },
      { key: "강릉", value: "강원도 강릉" },
      { key: "동해", value: "강원도 동해" },
      { key: "태백", value: "강원도 태백" },
      { key: "속초", value: "강원도 속초" },
      { key: "삼척", value: "강원도 삼척" },
      { key: "홍천", value: "강원도 홍천" },
      { key: "횡성", value: "강원도 횡성" },
      { key: "영월", value: "강원도 영월" },
      { key: "평창", value: "강원도 평창" },
      { key: "정선", value: "강원도 정선" },
      { key: "철원", value: "강원도 철원" },
      { key: "화천", value: "강원도 화천" },
      { key: "양구", value: "강원도 양구" },
      { key: "인제", value: "강원도 인제" },
      { key: "고성", value: "강원도 고성" },
      { key: "양양", value: "강원도 양양" },
    ],
  },
  {
    key: "충청북도",
    value: "충청북도",
    disabled: false,
    options: [
      { key: "청주", value: "충청북도 청주" },
      { key: "충주", value: "충청북도 충주" },
      { key: "제천", value: "충청북도 제천" },
      { key: "보은", value: "충청북도 보은" },
      { key: "옥천", value: "충청북도 옥천" },
      { key: "영동", value: "충청북도 영동" },
      { key: "증평", value: "충청북도 증평" },
      { key: "진천", value: "충청북도 진천" },
      { key: "괴산", value: "충청북도 괴산" },
      { key: "음성", value: "충청북도 음성" },
      { key: "단양", value: "충청북도 단양" },
    ],
  },
  {
    key: "충청남도",
    value: "충청남도",
    disabled: false,
    options: [
      { key: "당진", value: "충청남도 당진" },
      { key: "천안", value: "충청남도 천안" },
      { key: "공주", value: "충청남도 공주" },
      { key: "보령", value: "충청남도 보령" },
      { key: "아산", value: "충청남도 아산" },
      { key: "서산", value: "충청남도 서산" },
      { key: "논산", value: "충청남도 논산" },
      { key: "계룡", value: "충청남도 계룡" },
      { key: "금산", value: "충청남도 금산" },
      { key: "부여", value: "충청남도 부여" },
      { key: "서천", value: "충청남도 서천" },
      { key: "청양", value: "충청남도 청양" },
      { key: "홍성", value: "충청남도 홍성" },
      { key: "예산", value: "충청남도 예산" },
      { key: "태안", value: "충청남도 태안" },
    ],
  },
  {
    key: "전라남도",
    value: "전라남도",
    disabled: false,
    options: [
      { key: "목포", value: "전라남도 목포" },
      { key: "여수", value: "전라남도 여수" },
      { key: "순천", value: "전라남도 순천" },
      { key: "나주", value: "전라남도 나주" },
      { key: "광양", value: "전라남도 광양" },
      { key: "담양", value: "전라남도 담양" },
      { key: "곡성", value: "전라남도 곡성" },
      { key: "구례", value: "전라남도 구례" },
      { key: "고흥", value: "전라남도 고흥" },
      { key: "보성", value: "전라남도 보성" },
      { key: "화순", value: "전라남도 화순" },
      { key: "장흥", value: "전라남도 장흥" },
      { key: "강진", value: "전라남도 강진" },
      { key: "해남", value: "전라남도 해남" },
      { key: "영암", value: "전라남도 영암" },
      { key: "무안", value: "전라남도 무안" },
      { key: "함평", value: "전라남도 함평" },
      { key: "영광", value: "전라남도 영광" },
      { key: "장성", value: "전라남도 장성" },
      { key: "완도", value: "전라남도 완도" },
      { key: "진도", value: "전라남도 진도" },
      { key: "신안", value: "전라남도 신안" },
    ],
  },
  {
    key: "전라북도",
    value: "전라북도",
    disabled: false,
    options: [
      { key: "전주", value: "전라북도 전주" },
      { key: "군산", value: "전라북도 군산" },
      { key: "익산", value: "전라북도 익산" },
      { key: "정읍", value: "전라북도 정읍" },
      { key: "남원", value: "전라북도 남원" },
      { key: "김제", value: "전라북도 김제" },
      { key: "완주", value: "전라북도 완주" },
      { key: "진안", value: "전라북도 진안" },
      { key: "무주", value: "전라북도 무주" },
      { key: "장수", value: "전라북도 장수" },
      { key: "임실", value: "전라북도 임실" },
      { key: "순창", value: "전라북도 순창" },
      { key: "고창", value: "전라북도 고창" },
      { key: "부안", value: "전라북도 부안" },
    ],
  },
  {
    key: "경상북도",
    value: "경상북도",
    disabled: false,
    options: [
      { key: "포항", value: "경상북도 포항" },
      { key: "경주", value: "경상북도 경주" },
      { key: "김천", value: "경상북도 김천" },
      { key: "안동", value: "경상북도 안동" },
      { key: "구미", value: "경상북도 구미" },
      { key: "영주", value: "경상북도 영주" },
      { key: "영천", value: "경상북도 영천" },
      { key: "상주", value: "경상북도 상주" },
      { key: "문경", value: "경상북도 문경" },
      { key: "경산", value: "경상북도 경산" },
      { key: "군위", value: "경상북도 군위" },
      { key: "의성", value: "경상북도 의성" },
      { key: "청송", value: "경상북도 청송" },
      { key: "영양", value: "경상북도 영양" },
      { key: "영덕", value: "경상북도 영덕" },
      { key: "청도", value: "경상북도 청도" },
      { key: "고령", value: "경상북도 고령" },
      { key: "성주", value: "경상북도 성주" },
      { key: "칠곡", value: "경상북도 칠곡" },
      { key: "예천", value: "경상북도 예천" },
      { key: "봉화", value: "경상북도 봉화" },
      { key: "울진", value: "경상북도 울진" },
      { key: "울릉", value: "경상북도 울릉" },
    ],
  },
  {
    key: "경상남도",
    value: "경상남도",
    disabled: false,
    options: [
      { key: "창원", value: "경상남도 창원" },
      { key: "진주", value: "경상남도 진주" },
      { key: "통영", value: "경상남도 통영" },
      { key: "사천", value: "경상남도 사천" },
      { key: "김해", value: "경상남도 김해" },
      { key: "밀양", value: "경상남도 밀양" },
      { key: "거제", value: "경상남도 거제" },
      { key: "양산", value: "경상남도 양산" },
      { key: "의령", value: "경상남도 의령" },
      { key: "함안", value: "경상남도 함안" },
      { key: "창녕", value: "경상남도 창녕" },
      { key: "고성", value: "경상남도 고성" },
      { key: "남해", value: "경상남도 남해" },
      { key: "하동", value: "경상남도 하동" },
      { key: "산청", value: "경상남도 산청" },
      { key: "함양", value: "경상남도 함양" },
      { key: "거창", value: "경상남도 거창" },
      { key: "합천", value: "경상남도 합천" },
      { key: "마산", value: "경상남도 마산" },
      { key: "진해", value: "경상남도 진해" },
    ],
  },
  {
    key: "제주도",
    value: "제주도",
    disabled: false,
    options: [
      { key: "제주", value: "제주도 제주" },
      { key: "서귀포", value: "제주도 서귀포" },
    ],
  },
];

function current_location_formatting(city, region, subregion) {
  console.log("current_location_formatting", city, region, subregion);

  // 주소 test Array [
  //   Object {
  //     "city": "의정부시",
  //     "country": "대한민국",
  //     "district": "의정부동",
  //     "isoCountryCode": "KR",
  //     "name": "의정부동 493-8",
  //     "postalCode": "11650",
  //     "region": "경기도",
  //     "street": "의정부동",
  //     "streetNumber": "493-8",
  //     "subregion": null,
  //     "timezone": "Asia/Seoul",
  //   },
  // ]
  // Object {
  //   "city": null,
  //   "country": "대한민국",
  //   "district": "평창읍",
  //   "isoCountryCode": "KR",
  //   "name": "하리 171-5",
  //   "postalCode": "25374",
  //   "region": "강원도",
  //   "street": "하리",
  //   "streetNumber": "171-5",
  //   "subregion": "평창군",
  //   "timezone": "Asia/Seoul",
  // },
  // Object {
  //   "city": "공주시",
  //   "country": "대한민국",
  //   "district": "계룡면",
  //   "isoCountryCode": "KR",
  //   "name": "32613",
  //   "postalCode": "32613",
  //   "region": "충청남도",
  //   "street": null,
  //   "streetNumber": null,
  //   "subregion": null,
  //   "timezone": "Asia/Seoul",
  // },
  // Object {
  //   "city": "인천광역시",
  //   "country": "대한민국",
  //   "district": "만수동",
  //   "isoCountryCode": "KR",
  //   "name": "효성상아아파트",
  //   "postalCode": "21542",
  //   "region": "인천광역시",
  //   "street": "만수동",
  //   "streetNumber": "905-3",
  //   "subregion": null,
  //   "timezone": "Asia/Seoul",
  // },
  // Object {
  //   "city": "서울특별시",
  //   "country": "대한민국",
  //   "district": "태평로1가",
  //   "isoCountryCode": "KR",
  //   "name": "서울특별시청",
  //   "postalCode": "04524",
  //   "region": "서울특별시",
  //   "street": "세종대로",
  //   "streetNumber": "110",
  //   "subregion": null,
  //   "timezone": "Asia/Seoul",
  // },
  // Object {
  //   "city": "세종특별자치시",
  //   "country": "대한민국",
  //   "district": "종촌동",
  //   "isoCountryCode": "KR",
  //   "name": "종촌동 663",
  //   "postalCode": "30064",
  //   "region": "세종특별자치시",
  //   "street": "종촌동",
  //   "streetNumber": "663",
  //   "subregion": null,
  //   "timezone": "Asia/Seoul",
  // },
  //     Object {
  //     "city": "제주시",
  //     "country": "대한민국",
  //     "district": "이도이동",
  //     "isoCountryCode": "KR",
  //     "name": "제주시청",
  //     "postalCode": "63208",
  //     "region": "제주특별자치도",
  //     "street": "광양9길",
  //     "streetNumber": "10",
  //     "subregion": null,
  //     "timezone": "Asia/Seoul",
  //   },
  //   Object {
  //     "city": "서귀포시",
  //     "country": "대한민국",
  //     "district": "안덕면",
  //     "isoCountryCode": "KR",
  //     "name": "화순리 844-3",
  //     "postalCode": "63530",
  //     "region": "제주특별자치도",
  //     "street": "화순리",
  //     "streetNumber": "844-3",
  //     "subregion": null,
  //     "timezone": "Asia/Seoul",
  //   },
  //구현
  //city, region, subregion 값 사용 ->
  //if city, region값이 같을 경우
  //특별/광역시이기 때문에 이름 두번 반복하여(ex)"서울 서울") 저장
  //if region == 제주특별자치도
  //city값에서 "시"를 빼고 앞에 제주도를 붙여 저장
  //else
  // city 값이 null일 경우 subregion가져옴 region + city(or subregion)앞 두글자
  var result;
  if (city == region) {
    result = city.substr(0, 2);
    console.log(result + " " + result);
    return result + " " + result;
  } else if (region == "제주특별자치도") {
    result = city.slice(0, -1);
    console.log("제주도" + " " + result);
    return "제주도" + " " + result;
  } else {
    if (city == null) {
      //읍
      result = subregion.substr(0, 2);
      console.log("city==null", region + " " + result);
      return region + " " + result;
    } else {
      //의정부시, 동두천시, 남양주시 3글자인게 있기 때문에 뒤에 "시"만 빼줌
      result = city.slice(0, -1);
      console.log(region + " " + result);
      return region + " " + result;
    }
  }
}
//searchMain에서 사용
const administrativeDistrictList = [
  { name: "서울", sido_sgg: "서울 서울", isSpecialCity: true, click: false },
  { name: "부산", sido_sgg: "부산 부산", isSpecialCity: true, click: false },
  { name: "대구", sido_sgg: "대구 대구", isSpecialCity: true, click: false },
  { name: "인천", sido_sgg: "인천 인천", isSpecialCity: true, click: false },
  { name: "대전", sido_sgg: "대전 대전", isSpecialCity: true, click: false },
  { name: "울산", sido_sgg: "울산 울산", isSpecialCity: true, click: false },
  { name: "세종", sido_sgg: "세종 세종", isSpecialCity: true, click: false },
  { name: "광주", isSpecialCity: false, click: false },
  { name: "경기도", isSpecialCity: false, click: false },
  { name: "강원도", isSpecialCity: false, click: false },
  { name: "충청북도", isSpecialCity: false, click: false },
  { name: "충청남도", isSpecialCity: false, click: false },
  { name: "전라남도", isSpecialCity: false, click: false },
  { name: "전라북도", isSpecialCity: false, click: false },
  { name: "경상남도", isSpecialCity: false, click: false },
  { name: "경상북도", isSpecialCity: false, click: false },
  { name: "제주도", isSpecialCity: false, click: false },
];

export {
  START_POINT_DATA,
  administrativeDistrictList,
  current_location_formatting,
};
